### ISSUE TITLE
Sugesstion

### ISSUE THREAD

**Issue by fontrendererobj** [bdttd000/twitch-account-creator#2]
Add the oauth token to the page where the mail and password is.

**Comment by bdttd000** [comment]
@fontrendererobj Could you clarify the concept of OAuth? Specifically, when you mention suggesting OAuth, are you referring to the scenario where a page is created solely on a virtual machine? In such a case, unauthorized individuals would be unable to access or steal your data. Additionally, since the data is volatile, closing the page without saving would result in permanent loss, so OAuth won't change anything, besides forcing us to log in.
